.TH SIGROK\-GTK 1 "January 15, 2012"
.SH "NAME"
sigrok\-gtk \- GTK+ based GUI for the sigrok logic analyzer software
.SH "SYNOPSIS"
.B sigrok\-gtk
.SH "DESCRIPTION"
.B sigrok\-gtk
is a cross-platform GTK+ based GUI for the
.B sigrok
logic analyzer software.
.SH "OPTIONS"
The
.B sigrok\-gtk
tool currently has no command-line options.
.SH "EXIT STATUS"
.B sigrok\-gtk
exits with 0 on success, 1 on most failures.
.SH "SEE ALSO"
\fBsigrok\-cli\fP(1),
\fBsigrok\-qt\fP(1)
.SH "BUGS"
Please report any bugs on the sigrok\-devel mailing list
.RB "(" sigrok\-devel@lists.souceforge.net ")."
.SH "LICENSE"
.B sigrok\-gtk
is covered by the GNU General Public License (GPL), version 3 or later.
.SH "AUTHORS"
Please see the individual source code files.
.PP
This manual page was written by Uwe Hermann <uwe@hermann\-uwe.de>.
It is licensed under the terms of the GNU GPL (version 2 or later).
