.TH SIGROK-GUI 1 "March 26, 2010"
.SH "NAME"
sigrok-gui \- GUI client for the sigrok logic analyzer software
.SH "SYNOPSIS"
.B sigrok-gui \fR[\fB\-hV\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR]
.SH "DESCRIPTION"
.B sigrok-gui
is a cross-platform GUI for the
.B sigrok
logic analyzer software.
.SH "OPTIONS"
The
.B sigrok-gui
tool has very few command line options, as most configuration elements are
available from the GUI itself.
.TP
.B "\-h, \-\-help"
Show a help text and exit.
.TP
.B "\-V, \-\-version"
Show version information and exit.
.SH "EXIT STATUS"
.B sigrok-gui
exits with 0 on success, 1 on most failures.
.SH "SEE ALSO"
\fBsigrok-cli\fP(1)
.SH "BUGS"
Please report any bugs on the sigrok-devel mailing list
.RB "(" sigrok-devel@lists.souceforge.net ")."
.SH "LICENSE"
.B sigrok-gui
is covered by the GNU General Public License (GPL), version 2 or later.
.SH "AUTHORS"
Please see the individual source code files.
.PP
This manual page was written by Uwe Hermann <uwe@hermann-uwe.de>.
It is licensed under the terms of the GNU GPL (version 2 or later).
